In [3]:
import pandas as pd
import glob

In [4]:
x = glob.glob(r'C:\Users\LucasMarquesGasparin\Desktop\Learning\TCC\Time Series\Data\*.csv')

In [5]:
x

['C:\\Users\\LucasMarquesGasparin\\Desktop\\Learning\\TCC\\Time Series\\Data\\1.csv',
 'C:\\Users\\LucasMarquesGasparin\\Desktop\\Learning\\TCC\\Time Series\\Data\\2.csv',
 'C:\\Users\\LucasMarquesGasparin\\Desktop\\Learning\\TCC\\Time Series\\Data\\3.csv',
 'C:\\Users\\LucasMarquesGasparin\\Desktop\\Learning\\TCC\\Time Series\\Data\\4.csv',
 'C:\\Users\\LucasMarquesGasparin\\Desktop\\Learning\\TCC\\Time Series\\Data\\5.csv',
 'C:\\Users\\LucasMarquesGasparin\\Desktop\\Learning\\TCC\\Time Series\\Data\\6.csv']

In [10]:
q = pd.read_csv(x[0], parse_dates = ['Time'])

In [11]:
q

,Time,Pulse_x,Pulse_y,BallPosX,BallPosY,BallSpeed,PosB,PosA,ScoreB,ScoreA,Resultado,Attacking,PosBUpDown,PosAUpDown
0,2019-11-06 10:27:23.153,0,0,72.0,99.0,5.0,69.0,22.0,0.0,0.0,Empate,A,Up,Stop
1,2019-11-06 10:27:23.154,0,0,72.0,99.0,5.0,69.0,22.0,0.0,0.0,Empate,A,Up,Stop
2,2019-11-06 10:27:23.155,0,0,73.0,98.0,5.0,68.0,22.0,0.0,0.0,Empate,A,Up,Stop
3,2019-11-06 10:27:23.156,0,0,73.0,98.0,5.0,68.0,22.0,0.0,0.0,Empate,A,Up,Stop
4,2019-11-06 10:27:23.157,0,0,73.0,98.0,5.0,67.0,22.0,0.0,0.0,Empate,A,Up,Stop
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
855125,2019-11-06 10:41:38.278,0,0,735.0,130.0,5.0,393.0,280.0,6.0,28.0,ScoreA,B,Stop,Stop
855126,2019-11-06 10:41:38.279,0,0,736.0,129.0,5.0,393.0,280.0,6.0,28.0,ScoreA,B,Stop,Stop
855127,2019-11-06 10:41:38.280,0,0,736.0,129.0,5.0,393.0,280.0,6.0,28.0,ScoreA,B,Stop,Stop
855128,2019-11-06 10:41:38.281,0,0,737.0,128.0,5.0,393.0,280.0,6.0,28.0,ScoreA,B,Stop,Stop
855129,2019-11-06 10:41:38.282,0,0,737.0,128.0,5.0,393.0,280.0,6.0,28.0,ScoreA,B,Stop,Stop